projects:
  # bosh
  - github: cloudfoundry/bosh
  - github: cloudfoundry/bosh-cli
  - github: cloudfoundry-community/jumpbox-boshrelease
  - github: cloudfoundry-incubator/bosh-vsphere-cpi-release
  
  # concourse
  - github: concourse/concourse
 
